export interface Procedure {
  slug: string
  title: string
  shortDescription: string
  icon: string
  doctorId: string
  category: 'IR' | 'Neurology' | 'Internal Medicine'
}

export const procedures: Procedure[] = [
  {
    slug: 'peripheral-artery-disease-pad',
    title: 'Peripheral Artery Disease (PAD)',
    shortDescription: 'Minimally invasive treatment to restore blood flow in narrowed or blocked arteries in the legs.',
    icon: 'Heart',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'liver-cancer',
    title: 'Liver Cancer',
    shortDescription: 'Targeted interventional radiology treatments for liver cancer including chemoembolization and radioembolization.',
    icon: 'Activity',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'kidney-cancer',
    title: 'Kidney Cancer',
    shortDescription: 'Image-guided ablation and embolization techniques for kidney tumors as alternatives to surgery.',
    icon: 'Stethoscope',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'uterine-fibroids',
    title: 'Uterine Fibroids',
    shortDescription: 'Uterine fibroid embolization (UFE) to shrink fibroids without surgery, preserving the uterus.',
    icon: 'Shield',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'varicose-veins',
    title: 'Varicose Veins Treatment',
    shortDescription: 'Endovenous laser therapy and sclerotherapy for varicose and spider veins with minimal downtime.',
    icon: 'Zap',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'deep-vein-thrombosis-dvt',
    title: 'Deep Vein Thrombosis (DVT) Treatment',
    shortDescription: 'Catheter-directed thrombolysis and mechanical thrombectomy to dissolve dangerous blood clots.',
    icon: 'Droplets',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'prostate-artery-embolization',
    title: 'Prostate Artery Embolization (PAE)',
    shortDescription: 'Non-surgical treatment for enlarged prostate (BPH) that reduces symptoms without side effects of surgery.',
    icon: 'Target',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'pelvic-congestion-syndrome',
    title: 'Pelvic Congestion Syndrome Treatment',
    shortDescription: 'Ovarian vein embolization to relieve chronic pelvic pain caused by varicose veins in the pelvis.',
    icon: 'CircleDot',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'bone-metastases',
    title: 'Bone Metastases Treatment',
    shortDescription: 'Targeted ablation and cement augmentation for painful bone metastases to improve quality of life.',
    icon: 'Bone',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'gi-bleeding',
    title: 'GI Bleeding Treatment',
    shortDescription: 'Angiographic embolization to stop gastrointestinal bleeding quickly and effectively.',
    icon: 'Syringe',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'dialysis-access',
    title: 'Dialysis Access Management',
    shortDescription: 'Creation and maintenance of dialysis fistulas and grafts to ensure reliable vascular access.',
    icon: 'Cable',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'chronic-back-pain',
    title: 'Chronic Back Pain Treatment',
    shortDescription: 'Image-guided spinal injections and minimally invasive procedures for lasting back pain relief.',
    icon: 'Spine',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'varicocele',
    title: 'Varicocele Treatment',
    shortDescription: 'Percutaneous embolization of varicoceles to relieve pain and improve fertility without open surgery.',
    icon: 'Waves',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'pulmonary-embolism',
    title: 'Pulmonary Embolism Treatment',
    shortDescription: 'Catheter-directed therapy and IVC filter placement for life-threatening pulmonary blood clots.',
    icon: 'Wind',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'venous-insufficiency',
    title: 'Venous Insufficiency Treatment',
    shortDescription: 'Endovenous ablation and stenting to treat chronic venous insufficiency and improve circulation.',
    icon: 'ArrowDownUp',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'stem-cell-therapy',
    title: 'Stem Cell Therapy & Regenerative Medicine',
    shortDescription: 'Cutting-edge regenerative treatments using stem cells to promote healing and tissue repair.',
    icon: 'Sparkles',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'genicular-artery-embolization',
    title: 'Genicular Artery Embolization (GAE) for Knee Pain',
    shortDescription: 'Minimally invasive embolization of genicular arteries to reduce chronic knee inflammation and pain.',
    icon: 'Crosshair',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'chronic-knee-pain',
    title: 'Chronic Knee Pain Treatment',
    shortDescription: 'Comprehensive interventional radiology approaches for persistent knee pain and osteoarthritis.',
    icon: 'SquareActivity',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'ivc-filters',
    title: 'IVC Filters',
    shortDescription: 'Placement and retrieval of inferior vena cava filters to prevent pulmonary embolism.',
    icon: 'Filter',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'compression-fracture',
    title: 'Compression Fracture (Kyphoplasty)',
    shortDescription: 'Balloon kyphoplasty to stabilize spinal compression fractures and relieve debilitating back pain.',
    icon: 'Vertebra',
    doctorId: 'dr-ayad-agha',
    category: 'IR',
  },
  {
    slug: 'neurology',
    title: 'Neurology Services',
    shortDescription: 'Comprehensive neurological evaluations, diagnostics, and treatment for conditions affecting the brain and nervous system.',
    icon: 'Brain',
    doctorId: 'dr-yazan-al-hasan',
    category: 'Neurology',
  },
]
